packages/nextjs/CHANGELOG.md
packages/nextjs/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/react/src/FlowgladContext.tsx
packages/react/src/FlowgladProvider.tsx
packages/server/CHANGELOG.md
packages/server/package.json
packages/server/src/requestHandler.ts
packages/shared/CHANGELOG.md
packages/shared/package.json
packages/types/CHANGELOG.md
packages/types/package.json
platform/docs/quickstart.mdx
platform/docs/setup-by-prompt.mdx
pnpm-workspace.yaml

- Better createRequestHandler docs
- Better flowgladServer docs
- authenticated => loadBilling

Custom Onboarding Improvements

---

.github/workflows/build-and-deploy-prod.yml

Restores our worklow to automatically deploy whenever we push to stable

Fix: Restore Build and Deploy on Stable

---

.github/workflows/build-and-deploy-prod.yml

- Restores the build and deploy prod workflow, but this time makes it dependent on the staging build and deploy workflow finishing

Fix Build and Deploy Prod Workflow

---

platform/flowglad-next/src/app/api/ping/route.ts
platform/flowglad-next/src/components/FileInput.tsx
platform/flowglad-next/src/components/forms/ProductFormFields.tsx
platform/flowglad-next/src/components/forms/SendInvoiceReminderEmailModal.tsx
platform/flowglad-next/src/db/schema/invoiceLineItems.ts
platform/flowglad-next/src/db/schema/prices.ts
platform/flowglad-next/src/scripts/createRetryBillingRun.ts
platform/flowglad-next/src/scripts/example.ts
platform/flowglad-next/src/scripts/importCustomersToProductVariantPurchase.ts
platform/flowglad-next/src/scripts/migrateStripeAccountToFlowglad.ts
platform/flowglad-next/src/scripts/openApiDoc.ts
platform/flowglad-next/src/scripts/updateUnkeyKeyTypes.ts
platform/flowglad-next/src/scripts/upgradeUnkeyApiKeysToSchema.ts
platform/flowglad-next/src/scripts/upsertCatalogsAndPurchases.ts
platform/flowglad-next/src/server/routers/invoicesRouter.ts
platform/flowglad-next/src/server/swagger.test.ts
platform/flowglad-next/src/server/swagger.ts
platform/flowglad-next/src/utils/hostedBillingApiHelpers.ts

- Adds tests to our OpenAPI spec, to ensure that it doesn't change without us knowing about it (via failed tests!)
- Adds testmode logging to our `ProductFormFields` component to debug when it has errors in development / staging

Add OpenAPI Unit Tests

---

packages/express/CHANGELOG.md
packages/express/package.json
packages/nextjs/CHANGELOG.md
packages/nextjs/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/server/CHANGELOG.md
packages/server/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json
packages/types/CHANGELOG.md
packages/types/package.json
platform/hosted-billing/package.json
platform/hosted-billing/pnpm-lock.yaml
platform/hosted-billing/src/app/(webapp)/[organizationId]/manage/BillingPage.tsx
playground/supabase-auth/app/layout.tsx

- Publish the latest SDK, which supports custom theming for colors for all of our billing UI
- Add consistent styling for the hosted billing portal to have continuity with our web app

Publish Flowglad Theme SDK, Style Hosted Billing Portal Using Latest SDK

---

platform/flowglad-next/src/email-templates/components/EmailButton.tsx
platform/flowglad-next/src/email-templates/customer-order-receipt.tsx
platform/flowglad-next/trigger.config.ts

- Package React DOM, which may help with trigger.dev intermittent failures of pipeable stream error

React dom might help with trigger.dev emails

---

platform/flowglad-next/src/app/api/hosted-billing/request-magic-link/route.ts
platform/hosted-billing/src/flowgladHostedBillingApi.ts

- Hosted billing env variables reconcile

Hosted Billing Environment Variable Reconciliation

---

platform/flowglad-next/src/utils/core.test.ts

Add Tests to Billing Portal URL Tab

---

platform/flowglad-next/src/app/api/hosted-billing/request-magic-link/route.ts
platform/flowglad-next/src/app/customers/CustomersTable.tsx
platform/flowglad-next/src/app/customers/[id]/CustomerDetailsBillingTab.tsx
platform/flowglad-next/src/utils/core.ts

Customer billing portal tab

---

platform/flowglad-next/src/app/customers/CustomersTable.tsx
platform/flowglad-next/src/app/customers/[id]/CustomerDetailsBillingTab.tsx
platform/flowglad-next/src/components/CopyableTextTableCell.tsx

- Cleans up the customer details page, including max width on the portal URL

Customer Details Cleanup

---

platform/flowglad-next/src/components/forms/PriceFormFields.tsx
platform/flowglad-next/src/components/ion/NumberInput.tsx

- Trial Periods on PriceFormFields working

Fix Trial Period Bug

---

platform/flowglad-next/src/app/api/webhook-supabase/route.ts

Fix Create User Supabase Route

---

platform/flowglad-next/package.json
platform/flowglad-next/src/app/api/webhook-supabase/route.ts
platform/flowglad-next/src/trigger/supabase/event-inserted.ts

- Fix event payload parsing in event-inserted trigger job

Fix Event Payload Parsing In event-inserted trigger job

---

.github/workflows/build-and-deploy-staging.yml

- fix action dependency name staging

fix action dependency name staging

---

platform/flowglad-next/llm-prompts/new-test-suite.txt

New test suite prompt

---

.github/workflows/build-and-deploy-prod.yml
platform/flowglad-next/tailwind.config.ts

- Fix tailwind configs
- remove unnecessary svix github action breaking ci cd

Fix tailwind

---

.windsurfrules
platform/flowglad-next/src/components/forms/PriceFormFields.tsx
platform/flowglad-next/src/db/schema/prices.ts
platform/flowglad-next/src/utils/core.ts
platform/flowglad-next/src/utils/svix.ts

- Add usageMeterId nullable usageMeterId column refinement

Fix Create Price Form 

---

.gitignore

gitignore .ion-target

---

platform/flowglad-next/src/app/settings/webhooks/WebhooksTable.tsx
platform/flowglad-next/src/server/routers/organizationsRouter.ts
platform/flowglad-next/src/types.ts
platform/flowglad-next/src/utils/events.ts
platform/flowglad-next/src/utils/svix.ts

- Fix: Svix integration in production (internal)
- Fix: organization teammates table not showing your teammates because of RLS (internal)

Fix Svix + Organization Teammates Table

---

gameplans/destination_accounts.md

- Create a gameplan for destination accounts

dest acct gameplan

---

platform/flowglad-next/src/db/schema/organizations.ts
platform/flowglad-next/src/stack.tsx
platform/flowglad-next/src/subscriptions/createSubscription.test.ts
platform/flowglad-next/src/subscriptions/createSubscription.ts
platform/flowglad-next/src/utils/backendCore.ts
platform/flowglad-next/src/utils/organizationHelpers.ts

- Fix bug with subscription creation -> billing run logic (internal)
- Fix organization security salt not null (internal)

More Bugfixes (internal)

---

platform/flowglad-next/llm-prompts/changelog-announcement-message.txt

- New base prompt to generate chongelog emails (internal)

[internal] Changelog Base Prompt

---

gameplans/usage-aggregation/product-spec.md
platform/flowglad-next/drizzle-migrations/0210_wooden_thunderbolts.sql
platform/flowglad-next/drizzle-migrations/meta/0210_snapshot.json
platform/flowglad-next/drizzle-migrations/meta/_journal.json
platform/flowglad-next/src/app/customers/CustomersTable.tsx
platform/flowglad-next/src/db/schema/usageCreditBalanceAdjustments.ts
platform/flowglad-next/src/db/tableMethods/usageCreditBalanceAdjustmentMethods.ts
platform/flowglad-next/src/utils/backendCore.ts

- Usage Balance Balance Credit Adjustment table, part of the usage aggregation saga

Usage Aggregation: Usage Balance Credit Adjustments Table

---

gameplans/usage-aggregation/tickets.md
platform/flowglad-next/drizzle-migrations/0213_opposite_mercury.sql
platform/flowglad-next/drizzle-migrations/meta/0213_snapshot.json
platform/flowglad-next/drizzle-migrations/meta/_journal.json
platform/flowglad-next/llm-prompts/new-db-table.txt
platform/flowglad-next/src/db/schema/subscriptionMeterPeriodCalculations.ts
platform/flowglad-next/src/db/tableMethods/subscriptionMeterPeriodCalculationMethods.ts
platform/flowglad-next/src/db/tableUtils.ts
platform/flowglad-next/src/db/testEnums.ts
platform/flowglad-next/src/scripts/testDatabaseEnums.ts
platform/flowglad-next/src/types.ts

- Adds the subscription meter period calculation table

Usage Aggregation: Subscription Meter Period Calculation

---

platform/flowglad-next/drizzle-migrations/0214_skinny_joseph.sql
platform/flowglad-next/drizzle-migrations/meta/0214_snapshot.json
platform/flowglad-next/drizzle-migrations/meta/_journal.json
platform/flowglad-next/src/app/api/v1/[...path]/route.ts
platform/flowglad-next/src/components/forms/CreateFeatureModal.tsx
platform/flowglad-next/src/components/forms/EditFeatureModal.tsx
platform/flowglad-next/src/components/forms/FeatureFormFields.tsx
platform/flowglad-next/src/db/schema/features.ts
platform/flowglad-next/src/db/schema/prices.ts
platform/flowglad-next/src/db/schema/products.ts
platform/flowglad-next/src/db/tableMethods/featureMethods.ts
platform/flowglad-next/src/db/testEnums.ts
platform/flowglad-next/src/server/index.ts
platform/flowglad-next/src/server/routers/featuresRouter.ts
platform/flowglad-next/src/server/swagger.test.ts
platform/flowglad-next/src/types.ts

- Introduces the features table, that users can use to track the functionality in their app and (in future PRs) can use to grant access based on their customers' plans
- (internal) added test coverage to prevent passing organizationId updates to our REST API

Features: initial table

---

platform/flowglad-next/src/components/ErrorLabel.tsx
platform/flowglad-next/src/components/PaymentForm.tsx
platform/flowglad-next/src/trigger/notifications/send-customer-payment-succeeded-notification.ts

- Add error label + email validation on payment form to validate emails

Error Label and Email Validation on Payment Form

---

platform/flowglad-next/src/components/forms/PriceFormFields.tsx

- Fix a bug where changing from single to subscription price disables your ability to submit.

Price Form Fields Fix

---

platform/flowglad-next/src/components/forms/CreateProductModal.tsx
platform/flowglad-next/src/components/forms/DiscountFormFields.tsx
platform/flowglad-next/src/components/forms/PriceFormFields.tsx
platform/flowglad-next/src/db/schema/prices.test.ts
platform/flowglad-next/src/db/schema/prices.ts
platform/flowglad-next/src/stubs/priceStubs.ts

- Unit test coverage on transforming different price value defaults
- Use the unit tested objects in the default price form field
- Fix: Price Form Field default values when changing prices
- Fix Discount Form Fields' % bug

Fixes: Price Type Switch Unit Tests, Discount Form Percentage Field Bug

---

platform/flowglad-next/src/server/routers/productsRouter.ts
platform/flowglad-next/src/utils/catalog.test.ts
platform/flowglad-next/src/utils/catalog.ts

- Fix: create product operations now automatically enforce default price creation

Fix: Create Product Transaction Verifiably Creates Default Price

---

platform/flowglad-next/src/app/finance/subscriptions/[id]/page.tsx

- Internal: fix Promise params bug on subscription dynamic route params

Fix Subscription Details Dynamic Route Params

---

packages/express/CHANGELOG.md
packages/express/package.json
packages/nextjs/CHANGELOG.md
packages/nextjs/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/react/src/FlowgladTheme.tsx
packages/react/src/components/billing-page.tsx
packages/react/src/components/cancel-subscription-modal.tsx
packages/react/src/components/customer-billing-details.tsx
packages/react/src/components/invoices.tsx
packages/react/src/components/ui/button.tsx
packages/react/src/components/ui/dialog.tsx
packages/react/src/globals.css
packages/server/CHANGELOG.md
packages/server/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json
packages/types/CHANGELOG.md
packages/types/package.json
playground/supabase-auth/app/layout.tsx

- SDK: Stronger theming support on billing, with better resiliency to light mode / dark mode toggles
- SDK: Make cancel subscription modal compatible with the new scoped styling

SDK: Billing Page Enhancements

---

platform/flowglad-next/src/components/ActiveSubscribersChart.tsx
platform/flowglad-next/src/components/RecurringRevenueChart.tsx
platform/flowglad-next/src/components/RevenueChart.tsx

- Fix chart loading skeleton transition
- Make tooltips for subscribers be numbers rather than currency

Dashboard: Smoother Chart Loading Transition

---

platform/flowglad-next/drizzle-migrations/0222_colossal_hemingway.sql
platform/flowglad-next/src/app/hooks/usePriceFormContext.ts
platform/flowglad-next/src/components/forms/CreatePriceModal.tsx
platform/flowglad-next/src/components/forms/EditPriceModal.tsx
platform/flowglad-next/src/components/forms/OveragePriceSelect.test.tsx
platform/flowglad-next/src/components/forms/OveragePriceSelect.tsx
platform/flowglad-next/src/components/forms/PriceFormFields.tsx
platform/flowglad-next/src/components/forms/PriceFormTrialFields.tsx
platform/flowglad-next/src/components/navigation/Breadcrumb.test.tsx
platform/flowglad-next/src/components/navigation/Breadcrumb.tsx
platform/flowglad-next/src/scripts/migrateSingleSubscriptionBillingPeriod.ts
platform/flowglad-next/src/server/routers/pricesRouter.ts

- Add ability to configure credit trial prices via the dashboard
- Add ability to set overage price ids via the dashboard

Credit Trials Dashboard UI

---

platform/flowglad-next/drizzle-migrations/0223_shiny_terror.sql
platform/flowglad-next/drizzle-migrations/meta/0223_snapshot.json
platform/flowglad-next/drizzle-migrations/meta/_journal.json
platform/flowglad-next/llm-prompts/new-test-1-outline-test-cases.txt
platform/flowglad-next/llm-prompts/new-test-2-planning-stubs.txt
platform/flowglad-next/seedDatabase.ts
platform/flowglad-next/src/components/PaymentForm.tsx
platform/flowglad-next/src/contexts/checkoutPageContext.tsx
platform/flowglad-next/src/db/schema/checkoutSessions.ts
platform/flowglad-next/src/db/tableMethods/checkoutSessionMethods.ts
platform/flowglad-next/src/db/tableMethods/subscriptionMethods.ts
platform/flowglad-next/src/server/routers/checkoutSessionsRouter.ts
platform/flowglad-next/src/stubs/checkoutContextStubs.ts
platform/flowglad-next/src/stubs/checkoutInfoStubs.ts
platform/flowglad-next/src/utils/bookkeeping/confirmCheckoutSession.test.ts
platform/flowglad-next/src/utils/bookkeeping/processSetupIntent.test.ts
platform/flowglad-next/src/utils/bookkeeping/processSetupIntent.ts
platform/flowglad-next/src/utils/checkoutSessionState.ts

- Update payment method flow optionally updates all existing subscriptions to set them to have the new default payment method id

Add Payment Method Flow Updates All Subscriptions

---

platform/flowglad-next/src/components/forms/UsageMeterFormFields.tsx
platform/flowglad-next/src/server/routers/usageMetersRouter.ts

- Add slug form field to usage meter form fields

Add Slug Form Field to UsageMeterFormFields

---

platform/flowglad-next/src/app/customers/[id]/PurchasesTable.tsx
platform/flowglad-next/src/app/hooks/usePaginatedTableState.ts
platform/flowglad-next/src/components/ion/Table.tsx
platform/flowglad-next/src/db/schema/purchases.ts
platform/flowglad-next/src/db/tableMethods/purchaseMethods.ts
platform/flowglad-next/src/db/tableUtils.test.ts
platform/flowglad-next/src/db/tableUtils.ts

- Pagination first / last page support
- Purchase table improvements: better customer view, revenue on purchases wired through

Table improvements

---

platform/flowglad-next/src/db/authenticatedTransaction.ts
platform/flowglad-next/src/db/databaseAuthentication.ts

- Fixes authentication code in `databaseAuthentication`

Authenticated transaction fixes

---

platform/flowglad-next/src/components/PaymentForm.tsx
platform/flowglad-next/src/utils/bookkeeping/checkoutSessions.ts
platform/flowglad-next/src/utils/bookkeeping/confirmCheckoutSession.ts

- Fixes + observes a race condition caused by failed checkout session confirmations, plus then solves an issue with anon conditions

Confirm Checkout Session Race Condition

---

platform/flowglad-next/src/subscriptions/createSubscription/workflow.test.ts
platform/flowglad-next/src/subscriptions/subscriptionItemFeatureHelpers.test.ts
platform/flowglad-next/src/subscriptions/subscriptionItemFeatureHelpers.ts

- Add quantity to subscription item tests

Subscription Item Feature Quantity test coverage

---

platform/flowglad-next/src/middleware.ts

Fix Middleware

---

packages/nextjs/package.json
packages/nextjs/src/server.ts
packages/nextjs/src/withMCPToolAuthorization.ts
platform/flowglad-next/package.json
platform/flowglad-next/pnpm-lock.yaml
platform/flowglad-next/src/app/onboarding/page.tsx
platform/flowglad-next/src/components/ion/Navigation.tsx
platform/flowglad-next/src/components/navigation/ParentChildNavigationItem.tsx
platform/flowglad-next/src/components/navigation/StandaloneNavigationItem.tsx
platform/flowglad-next/src/db/client.ts
platform/flowglad-next/src/mcp/toolSet.ts
platform/flowglad-next/src/mcp/tools/echoTest.ts
platform/flowglad-next/src/mcp/tools/getDefaultCatalog.ts
platform/flowglad-next/src/mcp/tools/getSetupInstructions.ts
platform/flowglad-next/src/mcp/tools/instructions/mcp-setup.mdx
platform/flowglad-next/src/mcp/tools/instructions/nextjs-setup.mdx
platform/flowglad-next/src/mcp/tools/setupCatalog.ts
platform/flowglad-next/src/middleware.ts
platform/flowglad-next/src/server/routers/catalogsRouter.ts
platform/flowglad-next/src/utils/bookkeeping/createCheckoutSession.ts
platform/flowglad-next/src/utils/catalog.ts
platform/flowglad-next/src/utils/catalogs/setupTransaction.test.ts
platform/flowglad-next/src/utils/catalogs/setupTransaction.ts
playground/supabase-auth/app/[transport]/route.ts
playground/supabase-auth/package.json
playground/supabase-auth/pnpm-lock.yaml
playground/supabase-auth/utils/auth-helpers/server.ts
pnpm-lock.yaml

- Add Vercel MCP adapter to Nextjs SDK 
- Add tool for get default catalog, get setup instructions

SDK: Add MCP middleware

---

packages/express/CHANGELOG.md
packages/express/package.json
packages/nextjs/CHANGELOG.md
packages/nextjs/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/react/src/FlowgladTheme.tsx
packages/server/CHANGELOG.md
packages/server/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json
packages/types/CHANGELOG.md
packages/types/package.json
platform/flowglad-next/src/subscriptions/billingPeriodHelpers.ts

- Remove flowglad-root class from root element

SDK: Remove flowglad-root on root element

---

platform/flowglad-next/src/app/api/ping/route.ts
platform/flowglad-next/src/subscriptions/processBillingRunPaymentIntents.test.ts
platform/flowglad-next/src/subscriptions/processBillingRunPaymentIntents.ts
platform/flowglad-next/src/utils/email.ts

- Send payment failed notifications to both customer and organization on payment failed events

Payment Failed Notification

---

platform/flowglad-next/src/subscriptions/processBillingRunPaymentIntents.ts
platform/flowglad-next/src/utils/stripe.ts

- fix the invoice check in the payment method failed job (internal)
- Reverse transfer (internal)

Bug: fix invoice check in payment failed job

---

platform/flowglad-next/seedDatabase.ts
platform/flowglad-next/src/db/tableMethods/subscriptionItemFeatureMethods.test.ts
platform/flowglad-next/src/subscriptions/billingRunHelpers.ts
platform/flowglad-next/src/subscriptions/createSubscription/types.ts
platform/flowglad-next/src/subscriptions/createSubscription/workflow.test.ts
platform/flowglad-next/src/subscriptions/createSubscription/workflow.ts
platform/flowglad-next/src/trigger/notifications/send-organization-payment-failed-notification.ts
platform/flowglad-next/src/utils/bookkeeping/fees.test.ts
platform/flowglad-next/src/utils/bookkeeping/fees.ts
platform/flowglad-next/src/utils/bookkeeping/processPaymentIntentStatusUpdated.ts
platform/flowglad-next/src/utils/bookkeeping/processSetupIntent.ts

- Send organization payment failed notification

Send Organization Payment Failed Notification

---

platform/flowglad-next/src/db/tableMethods/invoiceMethods.test.ts
platform/flowglad-next/src/db/tableMethods/usageMeterMethods.test.ts
platform/flowglad-next/src/db/tableUtils.test.ts
platform/flowglad-next/src/db/tableUtils.ts
platform/flowglad-next/src/db/types.ts

- Reverses order on paginated table queries to be most recent first

Reverse Order On Paginated Payments

---

platform/flowglad-next/src/app/settings/ApiSettingsTab.tsx
platform/flowglad-next/src/server/routers/apiKeysRouter.ts
platform/flowglad-next/src/trigger/stripe/payment-intent-succeeded.ts
platform/flowglad-next/src/utils/eventHelpers.ts

- Add logic to trigger event insert for payment succeeded
- Filter out billing portal keys from the api table

Webhook on payment intent succeeded

---

platform/flowglad-next/src/app/onboarding/business-details/page.tsx

Fix Onboarding Form Field
